services:
  wordpress:
    image: wordpress:php8.3-apache
    container_name: destever-wordpress
    restart: unless-stopped
    ports:
      - "8159:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./live/wp-content:/var/www/html/wp-content

  db:
    image: mariadb:11
    container_name: destever-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: destever-redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
